#!/usr/bin/env python3
"""Regenerate README's endpoint tables from the FastAPI OpenAPI schemas.

The tables used to be maintained by hand and drifted through the api/hardware
split. Here they are derived from the apps themselves, and
`tests/api/test_readme_endpoints.py` fails when README no longer matches, so
adding a route without documenting it is a test failure rather than a surprise.

    python backend/scripts/gen_endpoint_docs.py           # rewrite README
    python backend/scripts/gen_endpoint_docs.py --check   # exit 1 on drift
"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
BACKEND_SRC = REPO_ROOT / "backend" / "src"

BEGIN = "<!-- BEGIN GENERATED ENDPOINTS -->"
END = "<!-- END GENERATED ENDPOINTS -->"

METHOD_ORDER = ["GET", "POST", "PUT", "PATCH", "DELETE"]


def _load_apps():
    """Import both apps. Must happen before their config modules read the env."""
    sys.path.insert(0, str(BACKEND_SRC))
    # Neither app has a usable default here: api/config.py raises without a
    # token when BREWCTL_IS_PROD=true, and mock hardware keeps the import free
    # of bluepy/RPi.GPIO.
    os.environ.setdefault("BREWCTL_IS_PROD", "false")

    from brewctl.api.server import app as api_app
    from brewctl.hardware.server import app as hardware_app

    return [("API service", api_app), ("Hardware service", hardware_app)]


def _rows(app) -> list[tuple[str, str, str]]:
    schema = app.openapi()
    rows: list[tuple[str, str, str]] = []
    for path, operations in schema.get("paths", {}).items():
        # The bundled frontend is mounted, not routed; documenting every static
        # asset path would bury the api.
        if path.startswith("/app"):
            continue
        for method, operation in operations.items():
            method = method.upper()
            if method not in METHOD_ORDER:
                continue
            summary = operation.get("summary") or ""
            description = (operation.get("description") or "").strip()
            # Prefer the first line of the docstring; summary is FastAPI's
            # title-cased function name and says little.
            text = description.splitlines()[0].strip() if description else summary
            rows.append((method, path, text))
    rows.sort(key=lambda r: (r[1], METHOD_ORDER.index(r[0])))
    return rows


def _sse_rows(app) -> list[tuple[str, str, str]]:
    """SSE routes carry no request body, so FastAPI documents them like any GET.

    They are separated out only because grouping the streams together is how a
    reader looks for them.
    """
    return [r for r in _rows(app) if r[1].startswith("/sse/")]


def render() -> str:
    lines = [BEGIN, "", "<!-- Generated by backend/scripts/gen_endpoint_docs.py -- do not edit by hand. -->"]
    for title, app in _load_apps():
        all_rows = _rows(app)
        streams = _sse_rows(app)
        rest = [r for r in all_rows if r not in streams]

        lines += ["", f"### {title}", ""]
        lines += ["| Method | Endpoint | Description |", "|--------|----------|-------------|"]
        for method, path, text in rest:
            lines.append(f"| {method} | `{path}` | {text} |")
        if streams:
            lines += ["", f"#### {title} — event streams", ""]
            lines += ["| Method | Endpoint | Description |", "|--------|----------|-------------|"]
            for method, path, text in streams:
                lines.append(f"| {method} | `{path}` | {text} |")
    lines += ["", END]
    return "\n".join(lines)


def apply(readme: Path, generated: str) -> str:
    text = readme.read_text()
    if BEGIN not in text or END not in text:
        raise SystemExit(
            f"{readme} has no {BEGIN} / {END} markers -- add them where the "
            "endpoint tables belong."
        )
    head, _, tail = text.partition(BEGIN)
    _, _, tail = tail.partition(END)
    return head + generated + tail


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="exit 1 if README is stale")
    parser.add_argument("--readme", type=Path, default=REPO_ROOT / "README.md")
    args = parser.parse_args()

    updated = apply(args.readme, render())
    if args.check:
        if updated != args.readme.read_text():
            print("README endpoint tables are stale -- run: make docs", file=sys.stderr)
            return 1
        return 0
    args.readme.write_text(updated)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
