import os

COLDBREW_SCALE_MAC_ADDRESS = os.environ['COLDBREW_SCALE_MAC_ADDRESS']
COLDBREW_INFLUXDB_TOKEN = os.environ['COLDBREW_INFLUXDB_TOKEN']
COLDBREW_INFLUXDB_URL = os.environ['COLDBREW_INFLUXDB_URL']
COLDBREW_INFLUXDB_ORG = os.environ['COLDBREW_INFLUXDB_ORG']

COLDBREW_INFLUXDB_BUCKET = 'coldbrew'
